# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "hashicorp/bionic64"
    config.vm.network "private_network", ip: "192.168.0.199"
    config.vm.hostname = "my-registry"
    config.vm.provision "file", source: "./docker-compose.yml", destination: "./docker-compose.yml"
    config.vm.provision "shell", path: "provision/install.sh", privileged: true
    
    config.vm.provider "virtualbox" do |v|
        v.memory = 512 
        v.cpus = 1
    end
end