version: '3.1'

services:
    postgres-teamcity:
        image: postgres:latest
        volumes:
            - postgres-teamcity-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: teamcity
            POSTGRES_USER: teamcity
            POSTGRES_DB: teamcity
        ports:
            - 5432:5432
        restart: unless-stopped

    teamcity:
        image: jetbrains/teamcity-server:2019.2
        volumes:
            - teamcity-server-datadir:/data/teamcity_server/datadir
            - teamcity-server-logs:/opt/teamcity/logs
        ports:
            - 8111:8111
        restart: unless-stopped
        
    teamcity-agent:
        image: aspnetcore/teamcity-agent-with-compose:2019.2
        build: ./agent
        environment:
            SERVER_URL: http://teamcity:8111
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped

volumes:
    postgres-teamcity-data:
    teamcity-server-datadir:
    teamcity-server-logs: